# Site settings
name: Charmaine Bonifacio
description: Academic Portfolio
google_analytics: UA-64593219-1
# Build settings
url: http://www.charmainebonifacio.com
permalink: pretty
markdown: kramdown
highlighter: pygmentsl
exclude:
    - LICENSE
    - README.md
    - CNAME
